FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

USER root

RUN dnf install -y python3 python3-pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "component.py"]