name: Test Changed Components
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required!
      
      - name: Detect changes
        id: changes
        uses: ./.github/actions/detect-changed-assets
      
      - name: Print all changes
        if: steps.changes.outputs.has-changes == 'true'
        run: |
          for component in ${{ steps.changes.outputs.all-changed-files }}; do
            echo "Changed file: $component"
          done

      - name: Print just changed components
        if: steps.changes.outputs.has-changed-components == 'true'
        run: |
          for component in ${{ steps.changes.outputs.changed-components }}; do
            echo "Changed component: $component"
          done


      - name: Print just changed pipelines
        if: steps.changes.outputs.has-changed-pipelines == 'true'
        run: |
          for component in ${{ steps.changes.outputs.changed-pipelines }}; do
            echo "Changed pipeline: $component"
          done

      - name: Detect changes
        id: filtered-changes
        uses: ./.github/actions/detect-changed-assets
        with:
          filter: '.*\.py$'

      - name: Print filtered changes
        if: steps.filtered-changes.outputs.has-changes == 'true'
        run: |
          for component in ${{ steps.filtered-changes.outputs.filtered-changed-files }}; do
            echo "Filtered changed file: $component"
          done